### ISSUE TITLE
[Feature]: Option to auto commit inline editor when editor looses focus

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#82] opened 2018-06-28 12:24 UTC
**I'm submitting a feature request**

* **Framework Version:**
current

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
Inline editors do not commit the value to the grid unless the user selects another cell or hits the enter/tab key. Some references to this issue include: 

https://coderwall.com/p/vztjkg/make-sure-slickgrid-commit-the-changes-when-click-on-submit-button-without-move-focus-out-of-the-input

https://github.com/mleibman/SlickGrid/issues/873

**Expected/desired behavior:**

* **What is the expected behavior?**
We could add a grid or editor option flag to commit on blur/focusout so the value in the editor is commited when the editor looses focus

* **What is the motivation / use case for changing the behavior?**
It is more natural for a user to change the value in an inline editor and then navigate away from the grid to either save the values or do something else. I wanted your thoughts on this to see if it will be a useful feature for this library. I have not solved it in my app yet because the select editors act different when the 
`focusoutevent` ocurrs, which is the event i was listening for.

![2018-06-28_08-17-45](https://user-images.githubusercontent.com/8404957/42033713-c6908518-7aab-11e8-8eb8-5d3644034910.gif)

**Comment by ghiscoding** [comment] 2018-06-28 12:55
That is a fair thinking, so I guess you will do a PR to address it? :-P

**Comment by jmzagorski** [comment] 2018-06-28 13:08
Yes, as soon as i figure out a good way to solve this I will submit a PR,

**Comment by jmzagorski** [comment] 2018-06-28 17:18
i have a solution that may work. now i just need to find time to make the PR

**Comment by ghiscoding** [comment] 2018-07-02 04:05
@jmzagorski 
Do you plan to have a PR this week or later? 

I'm asking because I just got Bootstrap 4 working, along with a brand new build with latest and greatest Aurelia & WebPack 4. I'm finally starting to go back to my personal project, after 6 months lol, and I want to give BS4 a try.

Anyhow, let me know if I should wait for your PR or just go with a patch release. I actually added a Decimal Formatter, but I'm not sure that deserves a minor release.

**Comment by jmzagorski** [comment] 2018-07-02 12:52
i will plan on trying to get in a PR today. I already have the changes in my app and would need to make some minor changes for this library

**Comment by jmzagorski** [comment] 2018-07-03 00:15
it is for the editor, but is it closer to the `autoedit` option that is set on the `gridOption`? Users do not set `autoEdit` on every editor so will users find it a pain to put 'autoCommit' on all their editors instead of `autoCommitEdits`on the `gridOption`? I guess it depends, in my situation users don't want every column behaving differently for committing the data to the grid, but that is just one case.  

Any different thoughts on that or do you still think the `editor` on the `column` is the right place?

**Comment by ghiscoding** [comment] 2018-07-03 00:54
Hmm I'm ok with both, if you are more into including it in the grid options then I'm fine with that. I don't think we need to pluralize it though, is there anything pluralized in the grid options? `autoCommitEdit` shoud be fine.

**Comment by jmzagorski** [comment] 2018-07-04 13:22
@ghiscoding don't wait for me on this because i ran into an unexpected issue and i am on vacation this week. I created a branch with my changes but because i am using the `focusout` event to try and commit changes on any editor, the validation popup will continually loop.

I could use `commitChanges` on the editors `args`, but then I would have to put logic in every editor, which i was trying to avoid because my solution was to be able to auto commit any editor, even custom editors, without having to put auto commit code in every editor (but i did have to make special exceptions for a few editors like the longtext, select editors and date editor)

Also, i am not sure if you will like this since it changes the behavior of some editors. As i was doing this i saw some editors already auto committed (ie. date and slider).  So i made sure they only auto committed when the grid option was set to keep the consistency, but you may not want that, Also, auto committing the slider on change is not too accurrate. The slider would have "49" before change and when it saves the final value shown is off by one or two numbers

**Comment by ghiscoding** [comment] 2018-07-04 13:56
@jmzagorski 
It's already Wednesday, so I will probably wait in the weekend to do a new release. I'm not sure if you will have it done by then, but if so then please let me know. 

I don't mind changing all Editors (including the custom one) if it makes this feature works better. 

As for the slider editor, I did see the value being off in a few times. I didn't really care but now that you've noticed it too, I think we'll have to fix it. I'm not sure if it's the displayed value that is late or if it's the serialized value that is delayed. I think it's a delay thing but that is just an assumption.

**Comment by ghiscoding** [comment] 2018-07-05 05:06
@jmzagorski 
I just fixed the Slider Editor accuracy with this [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/f21dba3edeba83b109d79dbdd847952a06187cab), it seems that using the `onmousemove` was adding some kind of delays and replacing that with `jQuery` event watch for `.on('input change')` works all the time. Also you might be wondering, why am I watching both `input` and `change` events... and the reason is to have cross-browser support. The `input[range]` does not have 1 common implementation, and so the multiple events, see this [SO](https://stackoverflow.com/a/33030129/1212166) which helped me fixed the issue. I tested in all browser (IE11, Edge, Firefox, Chrome, Opera) and it finally works across the board. 

The commit is on `master`, so please pull latest code to continue your testing with auto edit, also note that I changed the event from `change` to `mouseup` so that it works in IE11/Edge as well, without this change, these browsers were not even sliding which was weird.

**Comment by jmzagorski** [comment] 2018-08-07 00:48
I have the logic in my app, just haven't had time to test it in your library yet, and I need to check the slider works as well. I can start working on it tomorrow

**Comment by ghiscoding** [comment] 2018-08-07 13:25
@jmzagorski 
is that going to be a big change? 

I'm asking since `MultipleSelect` and `SingleSelect` Filters got reduced drastically, I merged the 2 files into 1 and I'm extending the master class with 1 boolean flag to know if it's a multiple select or not. So the new `SingleSelectFilter` will look like this 

currently just in my Angular repo, the code change was done yesterday in the long collection async refactoring.

```javascript
import { TranslateService } from '@ngx-translate/core';
import { CollectionService } from './../services/collection.service';
import { SelectFilter } from './selectFilter';

export class SingleSelectFilter extends SelectFilter {
  constructor(protected translate: TranslateService, protected collectionService: CollectionService) {
    super(translate, collectionService, false);
  }
}
```
all of the bulk is now in `SelectFilter` (previous `SelectFilter` got renamed to `NativeSelectFilter` since I wanted to use the name). This simplifies a lot the code (by 2x I guess lol)

**Comment by jmzagorski** [comment] 2018-09-14 19:08
@ghiscoding I am starting the change this afternoon

**Comment by ghiscoding** [comment] 2018-09-14 19:29
@jmzagorski 
Awesome thanks for the feedback.

I have couple of other small fixes that I'll push directly to the `master` branch. Have you ever noticed this [issue](https://github.com/ghiscoding/aurelia-slickgrid/commit/24a1bfad616fb554b22c4c7409be0742a56e6321) on your side? It only happens in Chrome and I got an opened [issue](https://github.com/6pac/SlickGrid/issues/275) on SlickGrid as well to track it

**Comment by jmzagorski** [comment] 2018-09-14 19:35
hmm I have not seem the horizontal scroll bar on my grids. However, I am only on version 1.13.1 of the lib, not sure if that matters.

**Comment by ghiscoding** [comment] 2018-09-14 19:44
It only happens on some computers and only on Chrome it seems. The problem is SlickGrid itself on how it calculates the scrollbar width. Anyhow, I've put code in place to compensate, so it won't show at all anymore. 

Have a nice weekend :)

**Comment by jmzagorski** [comment] 2018-09-15 12:50
Have you received any feedback from your users about how some editors (e.g. date, slider and long text) automatically focus on the next row editor when they save and destroy and others do not?

**Comment by ghiscoding** [comment] 2018-09-15 17:04
@jmzagorski 
This is mostly a behavior coming from SlickGrid core itself and I never really like that. The main problem, I think, is because you need to have `enableCellNavigation` set to True, else it doesn't work. But this `enableCellNavigation` has the tendency to try to go on the next line. So technically, all Editors should focus on the next row, if not then maybe it's related to how the `focus()` method is implemented (I'm not sure it's exactly that method but I would assume so).

**Comment by jmzagorski** [comment] 2018-09-15 19:50
I get around this by not using the `args.commitChanges` in the editor (if you look at that code it commits and focuses the next). Instead I use `args.grid.getEditorLock.commitChanges`. I replaced `args.commitChanges` in the save method of the other editors and they all behave the same by closing and not focusing on the next row. I can include that in my pull request if you like.

**Comment by ghiscoding** [comment] 2018-09-15 20:03
@jmzagorski 
That is interesting, but what you are talking about is in each Editor, isn't it? In that case, would it be possible to add a flag somewhere to possibly enable the usual behavior `args.commitChanges` and when disable, it could use the `args.grid.getEditorLock.commitChanges`? 

I mean, I really prefer your implementation which is without the navigate down behavior (like I said I don't personally like it), but not all users are the same and some might want this behavior. For example it could be useful when the grid is for input numbers which the user needs to enter multiple numbers in a column, and for that the flag would be better to have on that grid.

If you can add that trigger, it would be nice but if it's too much trouble then I'm still ok to remove navigate down behavior.

**Closed** 2018-09-27 18:56 UTC
Labels: enhancement
