### ISSUE TITLE
Export column width sets on wrong column, when export to excel

### ISSUE THREAD

**Issue by Chibi86** [ghiscoding/aurelia-slickgrid#511] opened 2021-01-25 10:29 UTC
### Your Environment

| Software          | Version(s) |
| ----------------- | ---------- |
| Aurelia           | 1.31 |
| Aurelia-Slickgrid | 3.1.0 |
| TypeScript        | 3.5.2 |
| Operating System  | Windows 10 |
| Node     | 10.15.3 | 
| NPM     |  6.4.1 |

### Context

I try to setup export to excel, and also set export width for columns.

### Expected Behavior
Title should get excel width on 50 point, when exporting.

### Current Behavior

![Screenshot_127](https://user-images.githubusercontent.com/6161062/105691965-2dead180-5efe-11eb-83c5-9f03dc31b605.png)
Title get default width on "8.43 points" in excel, when exporting.
![Screenshot_126](https://user-images.githubusercontent.com/6161062/105692180-638fba80-5efe-11eb-8b23-25b0890b3ccf.png)
But next column Duration gets 49.29 points, so it seems like width are of one column.

### Possible Solution

What I can see when console.log out sheet from customExcelHeader, some extra header styles (mark with red in image) is set before the real ones. Which makes all columns styles be of one column I think.
![Screenshot_129](https://user-images.githubusercontent.com/6161062/105693558-288e8680-5f00-11eb-8b92-a10545f76550.png)

### Code Sample

```
this.columnDefinitions1 = [
 { id: 'title', name: 'Title', field: 'title', sortable: true, minWidth: 100, exportColumnWidth: 50 },
 { id: 'duration', name: 'Duration (days)', field: 'duration', sortable: true, minWidth: 100 },
 { id: '%', name: '% Complete', field: 'percentComplete', sortable: true, minWidth: 100 },
 { id: 'start', name: 'Start', field: 'start', formatter: Formatters.dateIso },
 { id: 'finish', name: 'Finish', field: 'finish', formatter: Formatters.dateIso },
 { id: 'effort-driven', name: 'Effort Driven', field: 'effortDriven', sortable: true, minWidth: 100 }
];
this.gridOptions1 = {
  enableAutoResize: false,
  enableSorting: true,
  enableExcelExport: true,
  registerExternalResources: [new ExcelExportService()]
};
```

**Comment by Chibi86** [comment] 2021-01-25 10:49
> 
> 
> Yes widths are defined per column. Also your 50px get converted to Excels pts with regards to default font. See https://docs.microsoft.com/en-us/office/troubleshoot/excel/determine-column-widths#:~:text=In%20a%20new%20Excel%20workbook,correctly%20set%20to%20Arial%2010.

Did you really read the issue? I don't ask how columns width or excel width point works, I understand that. The issue is that export columns width is set on wrong column on export to excel.

**Comment by zewa666** [comment] 2021-01-25 12:36
Well your example set 50px to title. And your Excel Screenshot shows 8.43, which is the converted value. If you meant something different please elaborate

**Comment by Chibi86** [comment] 2021-01-25 13:33
> 
> 
> Well your example set 50px to title. And your Excel Screenshot shows 8.43, which is the converted value. If you meant something different please elaborate

Export column width are not in pixels: 
_You can define a custom Excel column width (the width Excel's own width which is not in pixel). You can define a custom width per column (in your column definitions) and/or for the entire grid (in your grid options)._
[Export to excel in wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Export-to-Excel#custom-column-width)

Here are the rest of the result:
![Screenshot_132](https://user-images.githubusercontent.com/6161062/105711882-6ba92380-5f19-11eb-9215-ca6315a28442.png)

One example where I remove export column width on title:
![Screenshot_133](https://user-images.githubusercontent.com/6161062/105712205-c6427f80-5f19-11eb-91a7-ec173c24bd23.png)

I been work with this issues two work days, so I have try things like this already.

**Comment by ghiscoding** [comment] 2021-01-25 14:04
@Chibi86 are you referring to this [Excel Custom Column Width - Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Export-to-Excel#custom-column-width)? The default is 10, you can see it on this [line](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/excel-export/src/excelExport.service.ts#L303) and I don't know if it really uses `pt` or `px`, that would depends on how that external lib `excel-builder.js`, sizing the cell seems to be displayed in this [page](http://web.archive.org/web/20160914041637/http://excelbuilderjs.com/cookbook/sizingColumns.html) info on that lib. If you spot any errors then let me know, but if I look at my implementation, it will first use `exportColumnWidth` or else the column width but I don't think it will necessarily be precise though. I never use custom width, it was implemented by another user in my other lib. 

Note `excel-build.js` is no longer supported by its original maintainer, the lib is still available and usable (and many other project like mine uses it) but don't expect any bug/fixes to ever be addressed on their side, even the docs are only available through the wayback machine since the original website no longer exists. So hopefully if there's anything, that would be in my code implementation

**Comment by Chibi86** [comment] 2021-01-25 14:49
> 
> 
> @Chibi86 are you referring to this [Excel Custom Column Width - Wiki](https://github.com/ghiscoding/aurelia-slickgrid/wiki/Export-to-Excel#custom-column-width)? The default is 10, you can see it on this [line](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/excel-export/src/excelExport.service.ts#L303) and I don't know if it really uses `pt` or `px`, that would depends on how that external lib `excel-builder.js`, sizing the cell seems to be displayed in this [page](http://web.archive.org/web/20160914041637/http://excelbuilderjs.com/cookbook/sizingColumns.html) info on that lib. If you spot any errors then let me know, but if I look at my implementation, it will first use `exportColumnWidth` or else the column width but I don't think it will necessarily be precise though. I never use custom width, it was implemented by another user in my other lib.
> 
> Note `excel-build.js` is no longer supported by its original maintainer, the lib is still available and usable (and many other project like mine uses it) but don't expect any bug/fixes to ever be addressed on their side, even the docs are only available through the wayback machine since the original website no longer exists. So hopefully if there's anything, that would be in my code implementation

Yes, I referring to "Excel Custom Column Width - Wiki". I can confirm it takes pt, if I move column width in excel file to right column were I have calculate text width in pt it fits perfectly.

What I can see in excelExport.service.js, if "grouping" is true it should add an extra columnStyle, which has the property "columnStyles" and the only one to have that in my example, is the extra one. I don't using column grouping, so it should not add an extra column style for that I think.

**Comment by ghiscoding** [comment] 2021-01-25 14:59
I'm not exactly sure what you mean by grouping, but PR (Pull Request) are welcome, so if know how to fix then please submit a PR in Slickgrid-Universal, thanks.

**Comment by Chibi86** [comment] 2021-01-25 15:23
What I mean is the variable grouping which is declared on [row 288](https://github.com/ghiscoding/slickgrid-universal/blob/master/packages/excel-export/src/excelExport.service.ts#L288) which is based on dataView.getGrouping().

**Comment by ghiscoding** [comment] 2021-01-25 15:38
The thing is that you now talk about grouping but that is not anywhere in your very short code sample & print screen in your original question. So again I'm not sure why you talk about grouping now? 

If you don't want to create a PR, you will have to at least provide a full code sample (on dumber or any other sandbox), I created that Excel Export Service 2 years ago, I don't fully recall on everything I wrote in that service. So please provide more steps and more code... or even better a PR to fix the issue.

**Comment by ghiscoding** [comment] 2021-01-25 23:22
@Chibi86 ok I see the problem after testing that in any of the grid, what you were trying to say (I think) is that `getGrouping()` returns an array and just testing with `if (grouping)` is not sufficient, instead if should be `if (Array.isArray(grouping) && grouping.length) {` and then that works as intended (as shown below)

![image](https://user-images.githubusercontent.com/643976/105778384-54c6f900-5f3a-11eb-8260-b32aab84e18a.png)

**Comment by Chibi86** [comment] 2021-01-26 07:38
Thanks a lot for the help, even if I might given to little information.

**Comment by ghiscoding** [comment] 2021-01-29 00:12
This is now fixed and released, however please note that you will have to **update both** Aurelia-Slickgrid `v3.3.0` and all Slickgrid-Universal packages `0.10.2` (there were some Typing changes that impacts both side).

**Closed by ghiscoding** 2021-01-29 00:12 UTC
Labels: bug, slickgrid-universal
