### ISSUE TITLE
Systemjs

### ISSUE THREAD

**Issue by johntom** [ghiscoding/aurelia-slickgrid#149] opened 2019-03-24 20:23 UTC
"aurelia-slickgrid": "^2.6.0"
"systemjs": "^0.21.5",
ESNext,
chrome Version 72.0.3626.121
nodejs: 10.15.0
windows10 
I have a current app using systemjs for cli and I've tried a numbr of things but can't seem to get slickgrid to work. In the following repo I've tried to replace requirejs with systemjs but no errors and nothing is displayed.
https://github.com/johntom/aurelia-cli-slickgrid-systemjs
another attempt to place the grid in the working project systemjs cli project displays the following and the dataset gets poplated as expected.
```
aurelia-logging-console.js:51 ERROR [app-router] TypeError: Cannot assign to read only property 
'dataset' of object '#<HTMLElement>'
    at Object.setValue (aurelia-binding.js:3732)
    at Binding.updateTarget (aurelia-binding.js:4986)
    at Binding.bind (aurelia-binding.js:5044)
    at View.bind (aurelia-templating.js:1700)
    at Controller.bind (aurelia-templating.js:3750)
    at Controller.automate (aurelia-templating.js:3695)
    at ready (router-view.js:171)
    at RouterView.swap (router-view.js:200)
    at aurelia-router.js:276
    at Array.forEach (<anonymous>)
    at aurelia-router.js:275
    at n (browser.js:1)
    at browser.js:1
    at MutationObserver.t (browser.js:1)
error @ aurelia-logging-console.js:51
```
```
{
  "name": "slickgrid-test-cli",
  "type": "project:application",
  "bundler": {
    "id": "cli",
    "displayName": "Aurelia-CLI"
  },
  "build": {
    "targets": [
      {
        "id": "web",
        "displayName": "Web",
        "port": 9000,
        "index": "index.html",
        "baseDir": ".",
        "output": "scripts"
      }
    ],
    "options": {
      "minify": "stage & prod",
      "sourcemaps": "dev & stage"
    },
    "bundles": [
      {
        "name": "app-bundle.js",
        "source": [
          "[**/*.js]",
          "**/*.{css,html}"
        ]
      },
      {
        "name": "vendor-bundle.js",
        "prepend": [
          "node_modules/bluebird/js/browser/bluebird.core.js",
          "node_modules/aurelia-cli/lib/resources/scripts/configure-bluebird.js",
          "node_modules/systemjs/dist/system.js"
        ],
        "dependencies": [
          "aurelia-binding",
          "aurelia-bootstrapper",
          "aurelia-dependency-injection",
          "aurelia-event-aggregator",
          "aurelia-framework",
          "aurelia-history",
          "aurelia-history-browser",
          "aurelia-http-client",
          "aurelia-loader",
          "aurelia-loader-default",
          "aurelia-logging",
          "aurelia-logging-console",
          "aurelia-metadata",
          "aurelia-pal",
          "aurelia-pal-browser",
          "aurelia-path",
          "aurelia-polyfills",
          "aurelia-route-recognizer",
          "aurelia-router",
          "aurelia-task-queue",
          "aurelia-templating",
          "aurelia-templating-binding",
          "text",
          "jquery",
          "moment",
          "text-encoding-utf-8",
          {
            "name": "i18next",
            "path": "../node_modules/i18next/dist/umd",
            "main": "i18next"
          },
          {
            "name": "aurelia-i18n",
            "path": "../node_modules/aurelia-i18n/dist/amd",
            "main": "aurelia-i18n"
          },
          {
            "name": "i18next-xhr-backend",
            "path": "../node_modules/i18next-xhr-backend/dist/umd",
            "main": "i18nextXHRBackend"
          },
          {
            "name": "aurelia-templating-resources",
            "path": "../node_modules/aurelia-templating-resources/dist/amd",
            "main": "aurelia-templating-resources"
          },
          {
            "name": "aurelia-templating-router",
            "path": "../node_modules/aurelia-templating-router/dist/amd",
            "main": "aurelia-templating-router"
          },
          {
            "name": "aurelia-testing",
            "path": "../node_modules/aurelia-testing/dist/amd",
            "main": "aurelia-testing",
            "env": "dev"
          },
          {
            "name": "bootstrap",
            "path": "../node_modules/bootstrap/dist",
            "main": "js/bootstrap.min",
            "deps": [
              "jquery"
            ],
            "exports": "$",
            "resources": [
              "css/bootstrap.css"
            ]
          },
	    {
            "name": "text",
            "path": "../node_modules/systemjs-plugin-text",
            "main": "text"
          },
          {
            "name": "flatpickr",
            "path": "../node_modules/flatpickr/dist",
            "main": "flatpickr.min",
            "resources": [
              "flatpickr.min.css",
              "l10n/fr.js"
            ]
          },
          {
            "name": "lodash.isequal",
            "path": "../node_modules/lodash.isequal",
            "main": "index"
          },
          {
            "name": "multiple-select",
            "path": "../node_modules/aurelia-slickgrid/dist/lib/multiple-select",
            "main": "multiple-select",
            "resources": [
              "multiple-select.css"
            ]
          },
          {
            "name": "aurelia-slickgrid",
            "path": "../node_modules/aurelia-slickgrid/dist/amd",
            "main": "index",
            "resources": [
              "**/*.{css,html}"
            ]
          },
          {
            "name": "jquery-event",
            "path": "../node_modules/slickgrid/lib",
            "main": "jquery.event.drag-2.3.0"
          },
          {
            "name": "slick-gridmenu",
            "path": "../node_modules/slickgrid/controls",
            "main": "slick.gridmenu.js"
          },
          {
            "name": "jquery-ui-dist",
            "path": "../node_modules/jquery-ui-dist",
            "main": "jquery-ui"
          },
          {
            "name": "slickgrid",
            "main": "slick.grid",
            "path": "../node_modules/slickgrid",
            "deps": [
              "jquery",
              "jquery-event",
              "jquery-ui-dist"
            ],
            "resources": [
              "controls/*.js",
              "plugins/*.js",
              "slick.groupitemmetadataprovider.js"
            ]
          },
          {
            "name": "dompurify",
            "main": "dist/purify",
            "path": "../node_modules/dompurify",
            "resources": []
          }
        ]
      }
    ],
    "loader": {
      "type": "system",
      "configTarget": "vendor-bundle.js",
      "includeBundleMetadataInConfig": "auto",
      "plugins": [
        {
          "name": "text",
          "extensions": [
            ".html",
            ".css"
          ],
          "stub": false
        }
      ]
    }
  },
  "platform": {
    "id": "web",
    "displayName": "Web",
    "port": 9000,
    "index": "index.html",
    "baseDir": ".",
    "output": "scripts"
  },
  "transpiler": {
    "id": "babel",
    "displayName": "Babel",
    "fileExtension": ".js",
    "options": {
      "plugins": [
        "transform-es2015-modules-amd"
      ]
    },
    "source": "src/**/*.js"
  },
  "markupProcessor": {
    "id": "minimum",
    "displayName": "Minimal Minification",
    "fileExtension": ".html",
    "source": "src/**/*.html"
  },
  "cssProcessor": {
    "id": "none",
    "displayName": "None",
    "fileExtension": ".css",
    "source": "src/**/*.css"
  },
  "editor": {
    "id": "vscode",
    "displayName": "Visual Studio Code"
  },
  "unitTestRunner": {
    "id": "karma",
    "displayName": "Karma",
    "source": "test/unit/**/*.js"
  },
  "paths": {
    "root": "src",
    "resources": "resources",
    "elements": "resources/elements",
    "attributes": "resources/attributes",
    "valueConverters": "resources/value-converters",
    "bindingBehaviors": "resources/binding-behaviors"
  },
  "testFramework": {
    "id": "jasmine",
    "displayName": "Jasmine"
  }
}

```

**Comment by ghiscoding** [comment] 2019-03-24 22:21
That's the problem with Aurelia, there's a little too much things to support to my taste. I have to admit that I was making sure to support the other CLI version with `RequireJS` but I didn't check for the past couple versions (it probable still works). However you said `SystemJS`, that's even worst, I never ever tried with `SystemJS`, my favorite is still `WebPack` based. Do you really have to use `SystemJS`? What would be the difference with `RequireJS`?

**Comment by johntom** [comment] 2019-03-24 23:28
I agree and understand the next version of Aurelia is make us very happy. I
develop with Frontendcreator.com and need to use systemjs

**Comment by ghiscoding** [comment] 2019-03-24 23:53
That's unfortunate, I don't know what causes it to not work, the only thing I can say is that if you find what causes the issue in the lib then I'm more than happy to receive and PR (Pull Request). But apart from that, I unfortunately don't have time to investigate in the matter.

**Comment by ghiscoding** [comment] 2019-03-25 00:32
After some thought, I suggest you to try an older version, perhaps version `2.4` (or even `2.0`) since version [2.5](https://github.com/ghiscoding/aurelia-slickgrid/releases/tag/v2.5.0) I reworked how the SlickGrid Plugins (columnPicker, gridMenu, ...) are imported, when I did that (in version `2.6`), I used the `require` and I'm not sure if that would work or break with `SystemJS`. For example, `require('slickgrid/controls/slick.columnpicker');`, this allowed me to cut down on the size of the lib, if user doesn't want to use some of the SlickGrid Plugin(s), don't it won't be imported. Also there's a lot of files & lib that you might need to import with `SystemJS`, I'm assuming it's similar to how `RequireJS` works and there was more info in the [README](https://github.com/ghiscoding/aurelia-slickgrid/wiki/HOWTO--Step-by-Step#2-for-aurelia-cli-modify-the-aureliajson-file).

Not sure if that will help, but it might be the cause of your issue. If that is the case then you might need to stick with an older version of the lib.

**Comment by johntom** [comment] 2019-03-25 01:49
Thanks, I will try some stuff later in week and get back to you. You’ve
done a great job with the library and is like to replace some if my kendoui
grid with slick grid. Fortuney I do have kendo working with systemjs And in
process if getting it all to work with circleci, my ultimate goal.

**Comment by johntom** [comment] 2019-03-25 21:02
I tried loading different version 2.4 & 2.0 without success. Will pick this up again...

**Comment by ghiscoding** [comment] 2019-04-17 03:33
@johntom 
I was looking at the Aurelia Weekly which I'm subscribed and it has a link to an old article on how to create an [Aurelia Plugin](http://patrickwalters.net/making-out-first-plugin/) in that article it mentions the JSPM configuration to add in the plugin `package.json` as follow
```json
"jspm": {
  "main": "index",
  "format": "amd",
  "directories": {
    "lib": "dist/amd"
  },
  "dependencies": {}
}
```
then the article explains it a bit more with the following
> The format property indicates which type of module system.js can expect to load. We specify amd at the moment due to some performance issues we ran in to with the system spec in early early alpha. You could choose any formats that system.js supports.

So I basically don't have any JSPM configuration in my `package.json`, could you try to run the sample you had done and then go into the `node_modules/aurelia-slickgrid` folder and modify the `package.json` with something like the following 
```json
"jspm": {
  "registry": "npm",
  "jspmPackage": true,
  "main": "index",
  "format": "amd",
  "directories": {
    "lib": "dist/amd"
  },
  "dependencies": {
      "aurelia-event-aggregator": ">=1.0.1",
      "aurelia-framework": ">=1.1.0",
      "aurelia-i18n": ">=2.1.0",
      "aurelia-pal": ">=1.4.0",
      "dompurify": "^1.0.7",
      "flatpickr": ">=4.2.4",
      "i18next-xhr-backend": ">=1.5.0",
      "jquery": ">=3.2.1",
      "jquery-ui-dist": "^1.12.1",
      "lodash.isequal": "^4.5.0",
      "moment": ">=2.18.1",
      "moment-mini": ">=2.18.1",
      "slickgrid": "^2.4.7",
      "text-encoding-utf-8": "^1.0.2"
  }
}
```

I'm assuming this will probably get you going and if that is it, I can surely update the `package.json` of the lib with it.

**Comment by ghiscoding** [comment] 2019-04-20 05:38
@johntom 
I added a new SystemJS demo in the [Aurelia-Slickgrid Demos](https://github.com/ghiscoding/aurelia-slickgrid-demos) and from what I can see, it's working fine on my end. There's probably something wrong in your setup somewhere but on my side it's working. 

However there are 2 things to note in my new [CLI-SystemJS demo](https://github.com/ghiscoding/aurelia-slickgrid-demos/tree/master/cli-systemjs-demo)
1. I tried using the `<require>` to use Aurelia-Slickgrid and other CSS files but I couldn't get it to work, so I've put them all in the `index.html` [here](https://github.com/ghiscoding/aurelia-slickgrid-demos/blob/master/cli-systemjs-demo/index.html#L6) and it's now working with that
2. I couldn't get `jquery.event.drag-2.3.0.js` to work, so I didn't include it my [aurelia.json](https://github.com/ghiscoding/aurelia-slickgrid-demos/blob/master/cli-systemjs-demo/aurelia_project/aurelia.json). It was building ok but it was throwing an error in the browser console when running, so I removed it. The grid seems to work just fine though.

With that, I'm really tempted to close this issue since I got a working SystemJS working (with latest Aurelia-CLI).

**Comment by ghiscoding** [comment] 2019-04-29 04:36
Received no feedback but I'll close since I have provided a new SystemJS example, see the [post](https://github.com/ghiscoding/aurelia-slickgrid/issues/149#issuecomment-485060588) just above for the link. I believe the issue is not in the lib itself. 

I can re-open if more info and tangible problem is provided.

**Closed by ghiscoding** 2019-04-29 04:36 UTC
Labels: need more info
