### ISSUE TITLE
[Bug]: adding onCellClick on editor column removes autoEdit , doesn't remove selectEditor

### ISSUE THREAD

**Issue by jmzagorski** [ghiscoding/aurelia-slickgrid#60] opened 2018-05-17 00:34 UTC
**I'm submitting a bug report**

**Current behavior:**
in `example3.ts` if you add an `onCellClick` to either select editor's column definition (% Complete or Prerequisite), it removes autoEdit and you have to double click to show the editor. Also, the single or multiple select editor stay open when clicking on another cell

**Expected/desired behavior:**
autoEdit stays enabled and editor goes away when moving to another cell

* **What is the motivation / use case for changing the behavior?**
I am doing advanced filtering in the select editor when the user clicks the cells. I want to change the `columnDef.params.collection` depending on the `dataContext`. I have not been able to figure out why these problems occur. Maybe the `autoEdit` turns off because of this [line](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/services/gridEvent.service.ts#L60).

Example of what I am doing. I have a grid of roles below and a column for users. Each row's multipleSelectEditor's collection should be filtered by the role column value (called title in the screenshot) to show the available users. You can also see the problem

![image](https://user-images.githubusercontent.com/8404957/40150480-ca4f6546-5947-11e8-9a48-a1e9559bc70a.png)

the logic:
```
    onCellClick: ({ columnDef, dataContext }) => {
      columnDef.params.collection = this.users.filter(c => c.roles.find(t =>
        dataContext.jobTitle && t.jobTitleName === dataContext.jobTitle.displayName));
    }

```

**Comment by ghiscoding** [comment] 2018-05-17 01:11
You should give a try to the regular `onCellClick` on the grid object and see if it works there. If that one also doesn't behave correctly there, then it's SlickGrid, else that would be something in gridEvent Service. 

With a the grid object
```javascript
grid.onCellChange.subscribe((e, args) => {
      console.log('onCellChange', args);
      this.updatedObject = args.item;
      this.resizer.resizeGrid(100);
    });
```
The example 3 has all the code (in the column or on the grid object), you just need to comment out the portion you don't want.

**Comment by jmzagorski** [comment] 2018-05-17 01:49
thanks for that suggestion. Using the grid's onClick event worked (a single clicked opens the editor and the select editor gets removed when clicking another cell). I can use this as a work around and leave this open so we can investigate when we have the time.

**Comment by ghiscoding** [comment] 2018-06-01 04:07
The issue is caused by this line `e.stopImmediatePropagation();` that is in fact inside the `onCellClick`. Clicking on the cell, was triggering the stop immediate and stopping the click event bubbling. 

I'm thinking about changing the signature of these 2 functions in our new Major release. I basically think that I should re-expose the event (just like SlickGrid does), so that the user can call a  `e.stopImmediatePropagation();` if he really wants to without affecting the behavior of the GridEventService

```diff
  /** an event that can be used for triggering an action after a cell change */
-  onCellChange?: (args: OnEventArgs) => void;
+  onCellChange?: (e: Event, args: OnEventArgs) => void;

  /** an event that can be used for triggering an action after a cell click */
-  onCellClick?: (args: OnEventArgs) => void;
+  onCellClick?: (e: Event, args: OnEventArgs) => void;
```

**Comment by ghiscoding** [comment] 2018-06-02 17:46
Exposed the Event as first argument in new upcoming `2,x` Major version. Closed by [commit](https://github.com/ghiscoding/aurelia-slickgrid/commit/2ac3cd86c4705bb47065b1252e4c401dc40cdba8)

**Closed by ghiscoding** 2018-06-02 17:46 UTC
Labels: bug
